"""Initial sourced observation tables.

Revision ID: 0001_observations
Revises:
"""

from alembic import op

revision = "0001_observations"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
    create table stocks (
      ticker varchar(12) primary key,
      name text not null
    );
    create table price_bars (
      id bigint generated by default as identity primary key,
      ticker varchar(12) not null references stocks(ticker),
      provider text not null,
      observed_at timestamptz not null,
      available_at timestamptz not null,
      ingested_at timestamptz not null default now(),
      open numeric(18,4) not null,
      high numeric(18,4) not null,
      low numeric(18,4) not null,
      close numeric(18,4) not null,
      volume bigint not null check (volume >= 0),
      unique (ticker, provider, observed_at),
      check (low <= high and open >= low and open <= high and close >= low and close <= high)
    );
    create index ix_price_ticker_available on price_bars(ticker, available_at);
    create table news_items (
      id bigint generated by default as identity primary key,
      provider text not null,
      source_key text not null,
      title text not null,
      url text not null,
      domain text not null,
      published_at timestamptz not null,
      available_at timestamptz not null,
      ingested_at timestamptz not null default now(),
      unique (provider, source_key)
    );
    create table news_ticker_links (
      id bigint generated by default as identity primary key,
      news_id bigint not null references news_items(id) on delete cascade,
      ticker varchar(12) not null references stocks(ticker),
      match_reason text not null,
      confidence text not null,
      unique (news_id, ticker)
    );
    create index ix_news_link_ticker on news_ticker_links(ticker);
    create table import_batches (
      id bigint generated by default as identity primary key,
      filename text not null,
      imported_at timestamptz not null default now(),
      row_count bigint not null
    );
    create table broker_flow_rows (
      id bigint generated by default as identity primary key,
      ticker varchar(12) not null references stocks(ticker),
      trading_date date not null,
      market varchar(2) not null,
      investor varchar(3) not null,
      broker varchar(8) not null,
      provider text not null,
      batch_id bigint not null references import_batches(id),
      buy_shares bigint not null,
      sell_shares bigint not null,
      buy_value bigint not null,
      sell_value bigint not null,
      buy_freq bigint not null,
      sell_freq bigint not null,
      available_at timestamptz not null,
      ingested_at timestamptz not null default now(),
      unique (ticker, trading_date, market, investor, broker, provider),
      check (buy_shares >= 0 and sell_shares >= 0 and buy_value >= 0 and sell_value >= 0 and buy_freq >= 0 and sell_freq >= 0)
    );
    create index ix_broker_ticker_available on broker_flow_rows(ticker, available_at);
    create index ix_broker_batch on broker_flow_rows(batch_id);
    create table provider_runs (
      id bigint generated by default as identity primary key,
      provider text not null,
      ticker text not null,
      status text not null,
      started_at timestamptz not null,
      finished_at timestamptz not null,
      error text
    );
    """)


def downgrade():
    op.execute("""
    drop table provider_runs;
    drop table broker_flow_rows;
    drop table import_batches;
    drop table news_ticker_links;
    drop table news_items;
    drop table price_bars;
    drop table stocks;
    """)
